Develop
BenjaminGarza/Project-Using-Bootstrap pull request #5
Opened 2019-08-06 15:41 UTC by BenjaminGarza

2019-08-06 20:45 UTC, Oghenebrume50 commented
Hi @BenjaminGarza  This is great work, I have a few corrections for you to implement though.
 - [ ] The NEWSWEEK logo at the top should be centred and there should be a date to the left of it.
- [ ] around the 669px width breakpoint the more stories section looks completely off, could you fix that

Great  work so far, make these changes and submit for re-review. BTW I noticed you didn't use [Github flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) please check it out but don't bother using it on this project, just keep it in mind for your next HTML projects, that's what you should be using.

2019-08-09 01:50 UTC, bolah2009 commented
Currently under review

2019-08-09 02:46 UTC, bolah2009 requested changes
## Almost there  :smile:  

The clone looks nice, however, I would suggest making sure **nothing is messed up** compared to the source page. There are some styling that is not implemented in the clone.
See below (check the full [page](https://www.newsweek.com/) for more section that needs to be worked on:

| Current | Preferred |
| :-----: | :-----: |
| ![bootstrap full current](https://user-images.githubusercontent.com/36057474/62749614-f3b11a00-ba54-11e9-9f7f-cb9db7bc0e02.gif) | ![bootstrap full preffered](https://user-images.githubusercontent.com/36057474/62749629-03306300-ba55-11e9-93bd-4ebc1555cc2b.gif) |

You can recreate this issue (Image above) by using the console on chrome **(Inspect `Ctrl+Shift+I`)** and the **Toggle device toolbar** `Ctrl+Shift+M`. This way you can simulate how the app will render on small to widescreen devices.


#### Friendly reminder: You should use Github Flow and [Linter](https://github.com/microverseinc/linters-config#linters-config) in this project. However, changing it now would take too much time. Please make sure you use Github Flow and [Linter](https://github.com/microverseinc/linters-config#linters-config) in the next project. You will find instructions in the Pathwright lesson description.


Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-08-09 02:46 UTC, bolah2009 commented on Main.css
> +
### `HINT`

Consider adding a smaller font size for the navigation bar for smaller screens. Also, the footer can use some repositioning for smaller screens. See illustration below:

| Current | Preferred |
| :-----: | :------: |
| ![bootstrap footer current](https://user-images.githubusercontent.com/36057474/62749163-47baff00-ba53-11e9-8352-3ff6abb578c0.png) | ![bootstrap footer preffered](https://user-images.githubusercontent.com/36057474/62749162-47226880-ba53-11e9-9015-a50c90016558.png) |

2019-08-09 02:46 UTC, bolah2009 commented on index.html
> +                <h6 class="more-stories-title">MORE STORIES</h6>
### `HINT`

Consider styling this and all other occurrences. (For example, giving it font color and weight as in the source page). See below:

| Current | Preferred |
| :-----: | :-----: |
| ![more stories current](https://user-images.githubusercontent.com/36057474/62750140-e5fc9400-ba56-11e9-961b-d508e5f79409.png) | ![more stories preffered](https://user-images.githubusercontent.com/36057474/62750149-edbc3880-ba56-11e9-9e0e-d3943c93ffa1.png) |

#### Do this for all other occurrences.

2019-08-13 00:39 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-13 00:46 UTC, Torres-ssf requested changes
### Hi there @BenjaminGarza 
You worked hard making these changes. But I notice that the stickler is not verifying your project. Maybe this is happening because it's not set up properly. Please check the instruction on the pathwrite on how to set up the linter and make it work on this project. You will also need to fix errors(if the linter found any). I know that in the past we didn't pay much attention to it but linting is important to reduce errors and improve the overall quality of your code. Using the linter also gives a professional look in your repository. 

Please kindly make this change and submit for code review again.
Happy coding :smile: 

[FOR FUTURE PROJECT]
 You should use Github/Git Flow in future projects. It's really easy to use it and will make your repository looks more professional. You will find instructions in the Patwright lesson description.

2019-08-14 02:53 UTC, Ispirett requested changes
Hey @BenjaminGarza @Oghenebrume50  Great! job with the changes requested by @Torres-ssf  and @bolah2009 
![image](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png). 

#### There are just a few things to address 
##### The Newsweek logo is too big
![fix1](https://user-images.githubusercontent.com/38801423/62991266-f2993780-be1c-11e9-8149-82f117382afe.png)

##### The content on the sides of the newsweek logo are to small.
![fix2](https://user-images.githubusercontent.com/38801423/62991271-fdec6300-be1c-11e9-8782-acdb5ddfd4a8.png)

2019-08-14 11:41 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-14 12:03 UTC, Torres-ssf approved these changes
### Hi there @BenjaminGarza 
I'm giving this project a :+1: 
Go on and merge to master. Good luck with the next one.

Friendly reminder: You should use Github/Git Flow in this project. However, changing it now would take too much time. Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.

2019-08-14 14:54 UTC, merged